-- AlterTable
ALTER TABLE "public"."User" ADD COLUMN     "blockReason" TEXT,
ADD COLUMN     "coverCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "currentPeriodStart" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "isBlocked" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "monthlyCoverLimit" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "monthlyResumeLimit" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "resumeCount" INTEGER NOT NULL DEFAULT 0;
